server:
   port: 10000
   contextPath: /sensehat

spring:
   application.name: SenseHatSpain

api.key: 6e4f94e2df81435f8af135d8112a5492

device:
   id: SenseHatSpain
   rest:
     local:
        schema: http
        ip: 192.168.1.10
     basepath: /sensehat
   register.fail.retry.seconds: 60
   ping.interval.seconds: 10
   logic.main.loop.delay.seconds: 5
   broker.rest:
      enable: true
      swaggerhost: localhost:10000

sofia2.digitaltwin.broker.rest: http://192.168.1.6:19300/digitaltwinbroker