sofia2:
   database.mongodb:
      servers: realtimedb:27017 
   iotbroker:
      server: http://iotbrokerservice:19000/iotbroker                  

spring:
   datasource:  
      url: jdbc:mysql://configdb:3306/sofia2_s4c?&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false            
      password: changeIt!   
   boot.admin: #Spring Boot Admin Config    
      url: http://monitoringuiservice:18100/monitoring
      client.service-url: http://${SERVER_NAME}${server.contextPath}/      
quartz:
    datasource:
      url: jdbc:mysql://schedulerdb:3306/sofia2_s4c_scheduler?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
      password: changeIt!  

              
## LOGGING CONF
logging:
   path: /var/log/logs-s4c 