server: ## Config Web Server
   port: 19200
   contextPath: /devicesimulator


# all access to actuator endpoints without security
management.security.enabled: false

spring:
   application.name: sofia2-device-simulator
   boot.admin: #Spring Boot Admin Config   
      url: http://localhost:18100
      username: operations
      password: changeIt!
      client.metadata.user.name: ${spring.boot.admin.username}
      client.metadata.user.password: ${spring.boot.admin.password}
   data.mongodb:
      database: sofia2_s4c # Database name.
  
   ## JPA Config
   datasource:
      url: jdbc:mysql://localhost:3306/sofia2_s4c?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
      username: root
      password: changeIt!
      driver-class-name: com.mysql.jdbc.Driver
      tomcat:
         # Number of ms to wait before throwing an exception if no connection is available.
         max-wait: 10000
         # Maximum number of active connections that can be allocated from this pool at the same time.
         max-active: 50
         # Validate the connection before borrowing it from the pool.
         test-on-borrow: true
         validation-query: SELECT 1
         test-while-idle: true
         test-on-borrow: true      
   jpa:
      ## Hibernate Properties
      # The SQL dialect makes Hibernate generate better SQL for the chosen database
      properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      # Hibernate ddl auto (create, create-drop, validate, update)
      properties.hibernate.hbm2ddl.auto: update

quartz:      
   datasource:
      # This property has to be configured in a profile in the pom.xml. Currently, it is configured in the parent project.
      url: "@sofia2.quartzURL@"
      username: root
      password: changeIt!
      driver-class-name: com.mysql.jdbc.Driver
      test-while-idle: true
      test-on-borrow: true
      validation-query: SELECT 1
   jpa:
      ## Hibernate Properties
      # The SQL dialect makes Hibernate generate better SQL for the chosen database
      properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      # Hibernate ddl auto (create, create-drop, validate, update)
      properties.hibernate.hbm2ddl.auto: update
      properties.hibernate.hbm2ddl.import_files: /quartz-schema.sql
   autoStartupSchedulers:
      - simulationScheduler
    
sofia2: #Config Sofia2 specific
   iotbroker:
      server: http://localhost:19000/iotbroker
   database.mongodb:
      database: sofia2_s4c
      authenticationDatabase:  #admin
      servers: localhost:27017
      autoConnectRetry: true
      socketTimeout: 5000
      maxAutoConnectRetryTime: 5000
      maxWaitTime: 5000
      useAuth: false
      username: #username
      password: #password
      readFromSecondaries: false
      queries.executionTimeout: 5000
      queries.defaultLimit: 150
      queries.maxConcurrentQueries: 3
      writeConcern: UNACKNOWLEDGED
      tools.mongoexport.path: mongoexport
      tools.mongoimport.path: mongoimport
      tools.mongoshell.path: mongo
      tools.useSequentialOps: true
   database.elasticsearch:
      database: sofia2_s4c_es
      sql.maxHttpConnections: 10
      sql.maxHttpConnectionsPerRoute: 10
      sql.connectionTimeout.millis: 10000
      sql.connector.http.endpoint: http://localhost:9200
      url: localhost
      port: 9300
            
## LOGGING CONF
logging:
   path: ./target/ 
   file: ${spring.application.name}
   level:
      com.indra: DEBUG 
