---
version: "2"

services:
  kadmin:
    hostname: kadmin
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      ZOOKEEPER_HOST: localhost:2181
      KAFKA_HOST: localhost:9092
      #SECURITY_PROTOCOL: SSL
      #TRUST_STORE_LOCATION: ssl/client.truststore.jks
      #TRUST_STORE_PASSWORD: password
      #KEY_STORE_LOCATION: ssl/server.keystore.jks
      #KEY_STORE_PASSWORD: password
      #KEY_PASSWORD: password