spring: ## General Config  
   datasource: ## JPA Config
      url: jdbc:mysql://configdb:3306/sofia2_s4c?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
## LOGGING CONF
logging:
   path: /var/log/logs-s4c 