##security.require_ssl: true

server: ## Config Web Server
   port: 30000
   contextPath: /scalability
   max-http-header-size: 10000000
   tomcat:
      access_log_enabled: true
      basedir: target/tomcat

spring: ## General Config  
   application.name: sofia2-scalability-example
   http:
      multipart:
         max-file-size: 200Mb
         max-request-size: 200Mb 
           
## LOGGING CONF
logging:
   level:
      com.indra: INFO
