version: "3"

services:  
  zookeeper:
    image: ${REPOSITORY}sofia2/zookeeper-secured:${IMAGETAG}
    container_name: zookeeper  
    ports:
     - "2181:2181"
    environment:
       ZOOKEEPER_CLIENT_PORT: "2181"
    network_mode: host
  kafka:
    image: ${REPOSITORY}sofia2/kafka-secured:${IMAGETAG}
    container_name: kafka    
    ports:
     - "9093:9093"
     - "9092:9092" 
    environment:
       KAFKA_ZOOKEEPER_CONNECT: "localhost:2181"
       KAFKA_ADVERTISED_LISTENERS: "SASL_PLAINTEXT://localhost:9093,PLAINTEXT://localhost:9092"
       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
    depends_on:
     - "zookeeper"      
    network_mode: host