version: "3"

services:  
  zookeeper:
    image: confluent/zookeeper:latest
    container_name: zookeeper  
    ports:
     - "2181:2181"
  kafka:
    image: confluent/kafka:latest 
    container_name: kafka    
    ports:
     - "9093:9093"
     - "9092:9092"  
    depends_on:
     - zookeeper       
  schema-registry:
    image: confluent/schema-registry:latest
    container_name: schema-registry    
    ports:
     - "8081:8081"
    depends_on:
     - zookeeper
     - kafka
  rest-proxy:
    image: confluent/rest-proxy:latest
    container_name: rest-proxy    
    ports:
     - "8082:8082"
    depends_on:
     - zookeeper
     - kafka  
     - schema-registry   
