sofia2:
   flowengine:
      node.path: node
      launcher:
         path: /opt/nodeRed/Flow-Engine-Manager
   database.mongodb:
      servers: realtimedb:27017 
      quasar.connector.http.endpoint: http://quasar:10800/query/fs/       
   database.elasticsearch:
      sql.connector.http.endpoint: http://elasticdb:9200
      url: elasticdb 
      port: 9300        

spring:
   datasource:  
      url: jdbc:mysql://configdb:3306/sofia2_s4c?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false            
   boot.admin: #Spring Boot Admin Config    
      url: http://monitoringuiservice:18100/monitoring
      client.service-url: http://${SERVERNAME}${server.contextPath}/ 
   data.mongodb:
      host: realtimedb
   elasticsearch.jest:
      uris: http://elasticdb:9200                
quartz:
    datasource:
      url: jdbc:mysql://schedulerdb:3306/sofia2_s4c_scheduler?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
      
## LOGGING CONF
logging:
   path: /var/log/logs-s4c 