#Integration Resources docker
sofia2:
  urls: 
    iotbroker:
      base: http://iotbrokerservice:19000/iotbroker
      advice: http://iotbrokerservice:19000/iotbroker/advice
    scriptingEngine:
      base:
      advice:
    flowEngine:
      base: https://s4citiespro.westeurope.cloudapp.azure.com/flowengine/
      advice: https://s4citiespro.westeurope.cloudapp.azure.com/nodered/
    routerStandAlone:
      base: http://localhost:20000/
      advice: http://localhost:20000/router/router/advice/
      management: http://localhost:20000/router/management/
      router: http://localhost:20000/router/router/
      hawtio: http://localhost:20000/hawtio/index.html
      swaggerUI: http://localhost:20000/router/swagger-ui.html
    apiManager:
      base: https://s4citiespro.westeurope.cloudapp.azure.com/api-manager/
      api: https://s4citiespro.westeurope.cloudapp.azure.com/api-manager/server/api/
      swaggerUI: https://s4citiespro.westeurope.cloudapp.azure.com/api-manager/swagger-ui.html?url=
      swaggerUIManagement: https://s4citiespro.westeurope.cloudapp.azure.com/api-manager/services/management/api-docs?url=/api-manager/services/management/swagger.json
      swaggerJson: https://s4citiespro.westeurope.cloudapp.azure.com/api-manager/services/management/swagger/
