security.ignored: /**

management.security.enabled: false

## Config Web Server
server:
   port: 19300
   contextPath: /digitaltwinbroker
spring:
  application.name: sofia2-digitaltwin-broker
  datasource:
    url: jdbc:mysql://localhost:3306/sofia2_s4c?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: changeIt!
    jpa:
      ## Hibernate Properties
      # The SQL dialect makes Hibernate generate better SQL for the chosen database
      properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      # Hibernate ddl auto (create, create-drop, validate, update)
      hibernate.ddl-auto: update
  boot.admin: #Spring Boot Admin Config    
    url: http://localhost:18100
    username: operations
    password: changeIt!
    client.metadata.user.name: ${spring.boot.admin.username}
    client.metadata.user.password: ${spring.boot.admin.password} 
    
sofia2: #Config Sofia2 specific
  digitaltwin.broker:
      rest:
        enable: true
        swaggerhost: localhost:19300   
  database.mongodb:
    database: sofia2_s4c
    authenticationDatabase:  #admin
    servers: localhost:27017
    autoConnectRetry: true
    socketTimeout: 5000
    maxAutoConnectRetryTime: 5000
    maxWaitTime: 5000
    useAuth: false
    username: #username
    password: #password
    readFromSecondaries: false
    queries.executionTimeout: 5000
    queries.defaultLimit: 150
    queries.maxConcurrentQueries: 3
    writeConcern: UNACKNOWLEDGED
    tools.mongoexport.path: mongoexport
    tools.mongoimport.path: mongoimport
    tools.mongoshell.path: mongo
    tools.useSequentialOps: true 
        
## LOGGING CONF
logging:
   path: ./target/ 
   file: ${spring.application.name}
   level:
      com.indra: DEBUG   
  