spring:
   datasource:  
      url: jdbc:mysql://configdb:3306/sofia2_s4c?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
   boot.admin: #Spring Boot Admin Config    
      url: http://monitoringuiservice:19000/monitoring
      client.service-url: http://${SERVER_NAME}${server.contextPath}/           
## LOGGING CONF
logging:
   path: /var/log/logs-s4c 