sofia2:
   database.mongodb:
      servers: realtimedb:27017 
      quasar.connector.http.endpoint: http://quasar:10800/query/fs/  
   urls:
    iotbroker: https://${SERVER_NAME}           
   flowengine.services:
    request.timeout.ms: 5000
    baseurl: http://flowengineservice:8082/sofia2/flowengine/admin   
    proxyurl: https://${SERVER_NAME}/nodered/             

spring:
   datasource:  
      url: jdbc:mysql://configdb:3306/sofia2_s4c?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false            
   boot.admin: #Spring Boot Admin Config    
      url: http://monitoringuiservice:18090      
quartz:
    datasource:
      url: jdbc:mysql://schedulerdb:3306/sofia2_s4c_scheduler?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false