sofia2:
   database.mongodb:
      servers: realtimedb:27017 
      quasar.connector.http.endpoint: http://quasar:10800/query/fs/
   database.elasticsearch:
      sql.connector.http.endpoint: http://elasticdb:9200
      url: elasticdb
      port: 9300
   urls:
    iotbroker: https://${SERVER_NAME}           
   flowengine.services:
    request.timeout.ms: 5000
    baseurl: http://flowengineservice:20100/flowengine/admin   
    proxyurl: https://${SERVER_NAME}/nodered/    
   webproject:
      rootfolder.path: /usr/local/webprojects/
      baseurl: https://${SERVER_NAME}/web/
   iotbroker.plugable:
     gateway:
      kafka:
        enable: true
        host: kafka
        port: 9095  
        user: admin
        password: admin-secret 
        partitions: 1
        replication: 1
   analytics.notebook:
      zeppelinHostname: zeppelin       
        
spring:
   datasource:  
      url: jdbc:mysql://configdb:3306/sofia2_s4c?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
   boot.admin: #Spring Boot Admin Config    
      url: http://monitoringuiservice:18100/monitoring    
      client.service-url: http://${SERVER_NAME}${server.contextPath}/ 
   data.mongodb:
      host: realtimedb
   elasticsearch.jest:
      uris: http://elasticdb:9200                   
quartz:
    datasource:
      url: jdbc:mysql://schedulerdb:3306/sofia2_s4c_scheduler?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
## LOGGING CONF
logging:
   path: /var/log/logs-s4c 