version: '2'
services:
  iotbrokerservice:
    scale: 1
    start_on_create: true
  apimanagerservice:
    scale: 1
    start_on_create: true
  loadbalancerservice:
    scale: 1
    start_on_create: true
  quasar:
    scale: 1
    start_on_create: true
  schedulerdb:
    scale: 1
    start_on_create: true
  devicesimulator:
    scale: 1
    start_on_create: true
  dashboardengineservice:
    scale: 1
    start_on_create: true
  flowengineservice:
    scale: 1
    start_on_create: true
  configdb:
    scale: 1
    start_on_create: true
  controlpanelservice:
    scale: 1
    start_on_create: true
  realtimedb:
    scale: 1
    start_on_create: true
  HAProxy:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: tcp
        service: iotbrokerservice
        source_port: 1883
        target_port: 1883
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
